version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-character-demo-backend
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=ai_character_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - USE_MOCK_AI=${USE_MOCK_AI:-false}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - AI_LAYER_URL=${AI_LAYER_URL}
    depends_on:
      - db
    volumes:
      - ./audio_samples:/app/audio_samples
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  db:
    image: postgres:15-alpine
    container_name: ai-character-demo-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai_character_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 