version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8082:8082"
    environment:
      - AI_SERVICE_URL=http://ai_layer:8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - ai_layer
      - redis
    networks:
      - ai_network

  ai_layer:
    build: 
      context: ../AI_Layer2
    environment:
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_LLAMA_ENDPOINT=${AZURE_LLAMA_ENDPOINT}
      - AZURE_API_KEY=${AZURE_API_KEY}
      - AZURE_MODEL_NAME=${AZURE_MODEL_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - ai_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - ai_network

networks:
  ai_network:
    driver: bridge